---
title: "Pink Bike Scraper"
output: html_notebook
---


### Essential Packages
```{r}
suppressMessages(library(tidyverse))
suppressMessages(library(rvest))
suppressMessages(library(xml2))
suppressMessages(library(jsonlite))
suppressMessages(library(ggplot2))
suppressMessages(library(gganimate))
suppressMessages(library(crosstalk))
suppressMessages(library(plotly))
suppressMessages(library(ggthemes))
suppressMessages(library(DT))
suppressMessages(library(stringr)) 
suppressMessages(library(lubridate))
```

### Scrape Pink Bike, Create Data Frame
```{r}
#Function to navigate to new URL and grab updated date for post
get_date <- function(session, link) {
              more_details_pg <- jump_to(session,link)  
              row_with_date <- html_node(more_details_pg,'tr:nth-child(4) td+ td')
              date_text <- str_extract(row_with_date %>% html_text(),
                         "([a-zA-Z]{3,}-[0-9]{1,2}-[0-9]{4}) ([0-9]{1,2}:[0-9]{2}:[0-9]{2})")
              return(date_text)
}

get_sold_status <- function(session, link) {
                      more_details_pg <- jump_to(session,link)  
                      row_with_sold <- html_node(more_details_pg,'td+ td span')
                      sold_status <- html_text(row_with_sold, trim=TRUE) 
                      return(sold_status)
}

```


```{r}
df_list <- list()

url <- paste("https://www.pinkbike.com/buysell/list/?location=194-*-*&page=1&category=2")

###Start web session. Imagine this is the script actively doing stuff on the page
session <- html_session(url)

### Find total results
total_count <- html_node(session, 'li:nth-child(13) a') %>% 
  html_text() %>% 
  as.numeric()
  
### Create vector of page results.  
pages <- c(1:total_count)

for (l in 1:length(pages))
{
new_url <- paste("https://www.pinkbike.com/buysell/list/?location=194-*-*&page=",pages[l],"&category=2", sep = "")
session <- html_session(new_url)
  title <- html_nodes(session, '.bsitem div a') %>% 
    html_text(trim = TRUE) 
  
  seller <- html_nodes(session, '.bsitem b+ a') %>% 
    html_text(trim = TRUE) 
   
  url <- html_nodes(session, '.bsitem div a') %>% 
    html_attr("href")
   
  dates <- get_more_links <- html_nodes(session, '.bsitem td:nth-child(1) a') %>%
    html_attr("href") %>% .[matches("buysell", vars=.)] %>% unique() %>%
    sapply(get_date,session = session) 
  
  sold <- get_more_links <- html_nodes(session, '.bsitem td:nth-child(1) a') %>%
    html_attr("href") %>% .[matches("buysell", vars=.)] %>% unique() %>%
    sapply(get_sold_status,session = session) 
 
  # condition <- html_nodes(session, 'br+ div') %>% 
  #   html_text(trim=TRUE) 
  
  
  # material <- html_nodes(session, '.bsitem div:nth-child(4)') %>% 
  #   html_text(trim=TRUE)
    
  
  # frame_size <- html_nodes(session, '.bsitem div:nth-child(5)') %>% 
  #   html_text(trim=TRUE) 
     
  
  # wheel_size <- html_nodes(session, '.bsitem div:nth-child(6)') %>% 
  #   html_text(trim=TRUE)
      
  
  # front_travel <- html_nodes(session, '.bsitem div:nth-child(7)') %>% 
  #   html_text(trim=TRUE) %>% 
  #   if(length(.) == 0) NA else .
       
  
  # rear_travel <- html_nodes(session, '.bsitem div:nth-child(8)') %>% 
  #   html_text(trim=TRUE)

  
  location <- html_nodes(session, '.bsitem td tr:nth-child(1) td') %>% 
    html_text(trim=TRUE) 
        
  
  price <- html_nodes(session, 'tr~ tr+ tr td > b') %>% 
    html_text(trim=TRUE)  
  
  df_list[[l]] <- tibble(title, seller, location, price, url,dates,sold)
}

df <- as_tibble(bind_rows(df_list)) 

```



### Data Prep to master dataframe
```{r}
### Remove duplicate posts
df<- distinct(df)

### Clean price column
df$price <- str_remove(df$price,"USD")
df$price <- as.integer(str_remove(df$price,"\\$"))

### Remove outliers
df <- df %>% 
  filter(price > 500 & price < 10000) 

### Create date columns and Sold/Available Flag
df <- df %>% 
  mutate(year = str_extract(df$title, "\\d{4}"),
         title = str_remove(df$title,"\\d{4}"),
         sold = ifelse(str_detect(df$sold, "Sold"),"Sold","Available")) %>% 
  rename(status = sold)

### Prep for string
df$title <- str_replace_all(df$title, "Santa Cruz", "Santa_Cruz")
df$title <- str_replace_all(df$title, "SANTA CRUZ", "Santa_Cruz")
df$title <- str_replace_all(df$title, "Rocky Mountain", "Rocky_Mountain")

df <- df %>% 
  mutate(title  = trimws(title))

### Create model and brand columns
df <- df %>% 
  mutate(brand = trimws(word(df$title,1,1,)),
         model = trimws(word(df$title,2,2,)),
         model = tolower(model),
         year = as.numeric(year)
         ) %>% 
  separate(location,c("city", "state", "country"), sep = ",", remove = FALSE)

### Convert date to datetime
df <- df %>% mutate(dates = mdy_hms(dates)) %>% rename(updated_at = dates)
print(df %>% summary())

```

### Create dataframe of sold bikes
```{r}
sold_df <- df %>% 
  filter(status == "Sold")

```


### Clean data and create child-dataframes for price analysis.  
####Parent dataframe = df.  Child dataframes = c("df_price","df_model_names")
```{r}
### Get list of most popular brands in dataset.  Brand has to appear > 30 times.
names <- df %>% 
    select(brand) %>% 
    group_by(brand) %>% 
    summarize(count = n()) %>% 
    filter(count >= 30, brand != c("Large", "Custom", "Stumpjumper", "Carbon"))

### Build df_price which can be used to measure % depreciation in asking price over time.
df_price <- df %>% 
  select(brand,price, year) %>% 
  filter(year >= 2013, brand %in% names$brand) %>% 
  group_by(brand,year) %>% 
  summarise(count = n(),avg_price = round(mean(price)))%>% 
  arrange(desc(year), .by_group = TRUE) %>% 
  mutate(pct_change = round((avg_price/lag(avg_price) - 1) * 100),
         pct_depreciation = round(avg_price/max(avg_price) * 100))

df_price$pct_change[is.na(df_price$pct_change)] <- 100


top_brands <- unique(names$brand)
df_price <- df_price %>% filter(brand %in% top_brands)

```


### Create df_model_price which is the data source for the shiny app. 
```{r}
### Create df for reactive filters
df_model_names <- df %>% 
  select(brand, model) %>% 
  filter(brand %in% top_brands) %>% 
  group_by(brand,model) %>% 
  summarise(count = n())

### Model has to appear at least 6 times to appear in data.
df_model_names <- df_model_names %>% filter(count >= 6)

### Create df for brand+model price analysis
df_model_price <- df %>% 
  select(title, brand,model,price, year, location, url, sold) %>%
  filter(year >= 2013, brand %in% names$brand, model %in% df_model_names$model) %>% 
  arrange(brand)



```


### Shiny UI
```{r}
library(shiny)
library(shinyWidgets)
ui <- fluidPage(

  # App title ----

  # Sidebar layout with input and output definitions ----

    # Main panel for displaying outputs ----
    mainPanel(
 titlePanel("A look at the asking price of used mountain bikes on Pinkbike.com"),
p("Use the filters below to explore how different bike models are priced and how asking-prices depreciate over time. Drag your cursor over specific points on the scatter plot to filter the table below it.  Double click anywhere in the chart to reset the filter"),



div(style="display: inline-block;vertical-align:top; width: 300px;", selectInput("select1", 
                              h3("Select Brand"), 
                              choices = unique(df_model_price$brand),
                              selected = NULL)),
      div(style="display: inline-block;vertical-align:top; width: 300px;",pickerInput("select2", 
                              h3("Select Model"),
                              choices = NULL,
                              options = list(`actions-box` = TRUE),
                              multiple = TRUE
                           
                              )),


      # Output: Histogram ----
      plotlyOutput("scatter"),

    fluidRow(
        column(12,
          DTOutput('table')
              )
            )
      
      #### IDEA.  Add data table details report below scatter.  Full add, make, model, location, year, price below average, 

    )
  )

```

### Server 
```{r}
server <- function(input, output,session) {
  
  
filter_model <- reactive({
                           filter(df_model_price, brand == input$select1)
                        })
   
  observeEvent(filter_model(), {
    choices <- unique(filter_model()$model)
    updatePickerInput(session,"select2", choices = choices, selected = choices) 
  })

  
  
  data <- reactive({
    df_model_price %>% filter(model %in% input$select2)
    })

 shared_data <- highlight_key(data, key = ~url)
 
 
  output$scatter <- renderPlotly({
    validate(
      need(!is.null(input$select2), "Loading...")
    )
  model_year <- reorder(shared_data$data()$year, desc(shared_data$data()$year))
    
  
   p <- ggplot(shared_data,aes(x = model_year, y = price)) + 
      geom_jitter(aes(color = NULL), size = 1)+
      stat_summary(fun.y=mean, geom="line",lwd=1,aes(group=2))+
    theme_tufte()+
  xlab("Model Year") +
  ylab("Asking Price") 
   
   
 ggplotly(p)%>% 
  highlight(on = "plotly_selected", off = "plotly_deselect", persistent = FALSE) 
   

  })
  
  
  output$table <- renderDT(

       shared_data$data(withSelection = TRUE) %>% filter(selected_ | is.na(selected_)) %>% 
                  mutate(url = paste0("<a href='",url,"'>",url,"</a>")),escape = FALSE) 
   

}




```

```{r}
shinyApp(ui, server)
```


