---
title: "R Notebook"

---

### Shiny Packages and Data Load
```{r}
library(shiny)
library(shinyWidgets)
suppressMessages(library(ggplot2))
suppressMessages(library(gganimate))
suppressMessages(library(crosstalk))
suppressMessages(library(plotly))
suppressMessages(library(ggdark))
suppressMessages(library(DT))
suppressMessages(library(scales))
suppressMessages(library(ggthemes))
library(shinythemes)

creds <- read.csv("/Users/t-carpen93/Data Projects/Credentials/creds.csv")
user <- as.character(creds[,2:2])
password <- as.character(creds[,3:3])

### Get data from DB.  Creds read from local file
cn <- dbConnect(RMySQL::MySQL(), 
          
                username = user, 
                password = password, 
                host = "shredsleds.ch4frojqjmlp.us-west-2.rds.amazonaws.com", 
                port = 3306,
                dbname = "bikes"
                )

query <- "SELECT * FROM model_price_view"
df_model_price <- dbGetQuery(cn, query)
dbDisconnect(cn)
```

### Align filters within bootsrap columns
###Align plotly graph within bootstrap columns
### Explore plotly themes

### User Experience
```{r}
ui <- bootstrapPage(theme = shinytheme("flatly"),
                  
h1("MTB Deal Spotter", 
      style = "font-family: 'Lato',
        font-weight: 400; line-height: 1.1; 
        color: #FFFFFF;
        text-align:center;
   background-color:#2C3E50;
   height:50px;
   bottom-padding: 25px;
   margin: 0px;"),

fluidRow( 
           div("",style="height:35px")
          ),

fluidRow( 
           column(3,""),
           column(6,p("Is this bike a good deal?   How is it priced compared to other models?   What price should I sell my bike for?") , 
                    p("Using data from pinkbike.com ads, we can explore how different bike models are priced and how asking-prices change over time.  This tool can also help you quickly spot potential deals"), align = "center"),
           column(3,"")),

fluidRow( 
          column(4,""),
          column(2, 
                 div(style="display: inline-block;vertical-align:top; align = center;width:100%;text-align:center", 
                        pickerInput("select1", 
                              h3("Select Brand"), 
                              choices = unique(df_model_price$brand),
                              selected = NULL))),
        
         column(2,
           div(style="display: inline-block;align = center;width:100%;text-align:center",
                 pickerInput("select2", 
                              h3("Select Model"),
                              choices = NULL,
                              options = list(`actions-box` = TRUE),
                              multiple = TRUE
                           
                              ))),

          column(4,"")
        ),

fluidRow( 
           div("",style="height:35px")
          ),

      # Output: Histogram ----
fluidRow( 
            column(3,""),
            column(6, div(plotlyOutput("scatter"),style="display: width:100%; align = center")),
            column(3,"")
          ),
fluidRow( 
           div("",style="height:35px")
          ),
fluidRow(
          column(2,""),
          column(8, div(DTOutput('table'),style="width:100%")),
          column(2,"")
        )
      


    )


```

### Server 
```{r}
server <- function(input, output,session) {
  
  
filter_model <- reactive({
                           filter(df_model_price, brand == input$select1)
                        })
   
  observeEvent(filter_model(), {
    choices <- unique(filter_model()$model)
    updatePickerInput(session,"select2", choices = choices, selected = choices) 
  })

  
  
  data <- reactive({
    df_model_price %>% filter(model %in% input$select2)
    })

 shared_data <- highlight_key(data, key = ~url)
 
 
  output$scatter <- renderPlotly({
    validate(
      need(!is.null(input$select2), "Loading...")
    )
  model_year <- reorder(shared_data$data()$year, desc(shared_data$data()$year))
    
  
   p <- ggplot(shared_data,aes(x = model_year, y = price)) + 
      geom_jitter(color = "#5DBC9B", size = 1)+
      stat_summary(fun.y=mean, geom="line",lwd=1,aes(group=2),color = "#2C3E50")+
    theme_fivethirtyeight()+
     theme(
          plot.title = element_text(color="#2C3E50", size=14, family="Lato"),
          plot.subtitle = element_text(color="#2C3E50", size=7, family="Lato"))+
  scale_y_continuous(labels = dollar)+
  labs(title = "Asking Price By Model Year")+
  xlab("Model Year")+
  ylab("Asking Price") 
   
   
 ggplotly(p)%>% 
  highlight(on = "plotly_selected", off = "plotly_deselect", persistent = FALSE) 
   

  })
  
  
  output$table <- renderDT(

       shared_data$data(withSelection = TRUE) %>% filter(selected_ | is.na(selected_)) %>% 
                  mutate(url = paste0("<a href='",url,"'>",url,"</a>")),escape = FALSE) 
   

}




```

```{r}
shinyApp(ui, server)
```